[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["cd ../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "cd ../.. && pnpm --filter @payos/types build",
  "cd ../.. && pnpm --filter @payos/utils build",
  "cd ../.. && pnpm --filter @payos/api build"
]

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production"

